language: php
php:
- 7.0
- 7.1
- 7.2
- hhvm

#before_script:
#- curl -s http://getcomposer.org/installer | php
#- php composer.phar install -n

script:
- php vendor/bin/codacycoverage clover build/coverage/xml

deploy:
  provider: heroku
    api_key:
      secure: f40a8b67-f15f-4319-8ca6-4615cc221a77
        app: pure-falls-59409

 notifications:
    slack: indusenvweb:oZMeAlo4UQ4Avox7k9ktHonq
    on_pull_requests: true
#    on_commits: true
    on_success: always
    on_failure: always